version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8u212-jdk-stretch
    steps:
      - checkout
      - run:
          name: Run Maven verify
          command: mvn clean verify
workflows:
  version: 2
  default:
    jobs:
      - test